# Generated by Django 4.1.7 on 2023-05-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('niveau', models.CharField(choices=[('Sixième', 'Sixième'), ('Cinquième', 'Cinquième'), ('Quatrième', 'Quatrième'), ('Troisième', 'Troisième')], max_length=200, null=True)),
                ('fichier', models.FileField(upload_to='pdfs/')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
